### ISSUE TITLE
Compat issue with Ma enchants

### ISSUE THREAD

**Issue by qwertyxcvb** [infernalstudios/Nekos-Enchanted-Books#24] opened 2022-06-28 23:53 UTC
It doesnt show texture for Ma enchants i even put mod resources on top and it still doesnt load does it have a problem with the version or optifine?

**Comment by nekomaster1000** [comment] 2022-06-28 23:54
This is because Ma Enchants changed it's modID between versions, it's a known issue and will be fixed in the next release.

**Comment by Dariensg** [comment] 2022-06-28 23:58
Duplicate of #22

**Closed by Dariensg** 2022-06-28 23:58 UTC
Labels: bug, duplicate
